library(plyr) 
library(dplyr)
library(ggplot2)

NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
df <- subset(SCC, select = c("SCC", "Short.Name"))
NEI <- merge(NEI, df, by.x="SCC", by.y="SCC", all=TRUE)

PLOT4 <- subset(NEI, grepl('oal',NEI$Short.Name, fixed=TRUE), c("Emissions", "year","type", "Short.Name"))
PLOT4 <- aggregate(Emissions ~ year, PLOT4, sum)
png(file = "PLOT4.png")
plot((Emissions / 1000) ~ year, data = PLOT4, type = "l", xlab = "Year",ylab = "Total emissions (/1000)", main = "Total US Coal Emissions",xaxt="n")
axis(side=1, at=c("1999", "2002", "2005", "2008"))
dev.off()
